apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: central-observability
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        args: ["server", "/data", "--console-address", ":9001"]
        env:
        - name: MINIO_ROOT_USER
          value: "minio"
        - name: MINIO_ROOT_PASSWORD
          value: "minio123"
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: central-observability
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: minio
---
apiVersion: v1
kind: Secret
metadata:
  name: tempostack-dev-minio
  namespace: central-observability
stringData:
  bucket: tempo
  endpoint: http://minio.central-observability.svc.cluster.local:9000
  access_key_id: minio
  access_key_secret: minio123
type: Opaque
